name: "parallelcoordinates.de"
description: "Visual Multidimensional Geometry"

# uncomment the following line to deploy on github:
baseurl: "/parallelcoordinates.de"

#baseurl: "http://localhost:4000"
#url: "http://julianheinrich.github.io
#url: "http:/"

paginate: 10

permalink: pretty
highlighter: pygments