name: "parallelcoordinates.de"
description: "Visual Multidimensional Geometry"

#url: "http://localhost:4000"
url: "http://julianheinrich.github.io/parallelcoordinates.de"

paginate: 10

permalink: pretty
highlighter: pygments