name: "parallelcoordinates.de"
description: "Visual Multidimensional Geometry"

baseurl: "/parallelcoordinates.de"
url: "http://localhost:4000"
#url: "http://julianheinrich.github.io/parallelcoordinates.de"
#url: "http://parallelcoordinates.de"

paginate: 10

permalink: pretty
highlighter: pygments