name: "parallelcoordinates.de"
description: "Visual Multidimensional Geometry"

baseurl: "/parallelcoordinates.de"
url: "http://localhost:4000"
#url: "http://julianheinrich.github.io
#url: "http:/"

paginate: 10

permalink: pretty
highlighter: pygments