name: "parallelcoordinates.de"
description: "Visual Multidimensional Geometry"

# uncomment the following line to deploy on github:
#baseurl: "/parallelcoordinates.de"

#baseurl: "http://localhost:4000"
#url: "http://julianheinrich.github.io
url: "http://"

paginate: 1
paginate_path: "tutorial/page:num/"

permalink: pretty
highlighter: pygments
#markdown: kramdown

exclude: [
  'scss',
  '*.rb',
  '*.yml', 
  'vendor', 
  'Gemfile', 
  'Gemfile.lock',
  '*.sh',
  'README.md',
  'LICENSE.md',
  'paper'
]

scholar:
  style: apa
  locale: en
  sort_by: year
  order: descending
  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: "{{ reference }}"
  replace_strings: true
  join_strings:    true
  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details
  query: "@*"
  #repository: ./files